### ISSUE TITLE
Incompatibility with .NET Framework 2.0 compiler

### ISSUE THREAD

**Issue by stephen147** [adrium/KeepassPfpConverter#2] opened 2019-06-24 10:11 UTC
Error msg:
![image](https://user-images.githubusercontent.com/14054664/60010973-be9d6380-9670-11e9-8552-8c2577c984fd.png)

**Comment by adrium** [comment] 2019-07-16 21:03
Thanks for reporting!

You seem to be the first person that tries the plugin. :tada:
That's also the reason why I haven't noticed the issue for some time.
Sorry about that, I simply did not expect that... :sweat_smile:

I would be interested in your use case. Can you tell me more about it?

My use case is that I use [my fork of PfP](https://github.com/adrium/easypass) for all passwords and credentials. To conveniently use them on my mobile as well, I convert the database from time to time and use it with [KeePass DX](https://www.keepassdx.com/).
The nice thing is that the converter creates [custom fields](https://github.com/adrium/KeepassPfpConverter#custom-fields) from notes which can directly be used in the Magikeyboard (for example CVVs for credit cards).

**Comment by adrium** [comment] 2019-07-16 21:08
The issue is fixed in d278d51.
There was an exception filter (catch when) which is only supported in C# 6 and above.

I have to admit that I don't actually test every release with Windows, because I use Linux with Mono.
But now the problem should not occur anymore. Can you confirm?

**Closed as completed** 2019-07-25 22:38 UTC
