### ISSUE TITLE
Issue with .NET Framework installation

### ISSUE THREAD

**Issue by artarik** [adrium/KeepassPfpConverter#3] opened 2021-02-09 10:14 UTC
Hi, I am a second men who use your plugin, thanks fot it :)
i have the same error like [this](https://github.com/adrium/KeepassPfpConverter/issues/2)
![image](https://user-images.githubusercontent.com/14920717/107348656-61218900-6ad8-11eb-8915-ce839048aee1.png)

- OS: Windows 10 2004 x64
- Keepas: Portable 2.47
- Plugin version 1.6

**Comment by adrium** [comment] 2021-02-28 10:39
Hi, nice to know that the plugin is used.

What version of the .NET Framework are you using?
I tried to run the plugin on Windows XP and .NET Framework 2.0 and it fails to compile due to:

    PfpConverter.cs(593,68): error CS0241: Default parameter specifiers are not permitted

Which is the following declaration:

    public PwEntryIndexer(PwEntry entry, ICollection<string> protect = null)

In case you are running a version older than 4, don't you think it's time to upgrade?

I will fix the bug, but it does not have high priority.

**Comment by artarik** [comment] 2021-02-28 12:22
i use .NET Framework 4.8

**Comment by adrium** [comment] 2021-02-28 17:24
I could not reproduce:

![debuginfo](https://user-images.githubusercontent.com/23739584/109427266-d7d3e700-79f1-11eb-873a-3f824ca42f83.jpg)

Can you supply the error file that is created with the `--debug` flag:

> **PLGX debugging.** When the command line option --debug is passed
> and a PLGX plugin fails to compile, the output of all tried compilers is saved to a temporary file.

https://keepass.info/help/v2_dev/plg_index.html

**Comment by artarik** [comment] 2021-03-01 06:06
hm.. I solved it by reinstalling .NetFramework.
Thanx

**Comment by adrium** [comment] 2021-03-02 08:10
Thanks for your feedback. Closing issue.

**Closed as completed by adrium** 2021-03-02 08:10 UTC
